### PR TITLE
Feature/registration and login

### PR DESCRIPTION
**Pull request by DeveloperAspire**
Here is a breakdown of what I did:

- Added the custom colors for MUI themes, without touching the original palette so we can still refer to it when we want.
- Revamped to the component to show how we can use the themes in components
- I also left the styled-components file
- Please let no ignore the eslint anymore
- Added base URL settings for absolute imports
- Added a file creation method, folders then index.tsx for neater code structure

Note: I didn't delete any of the styled-components files, just in case you feel there is a need for it.

### CODE REVIEW

**Comment by DeveloperAspire** [comment]
You are to merge it sir. Merge it if it is okay by you.

**Comment by drazomo** [comment]
There was a merge conflict when trying to merge this branch into dev. Ensure before you push to the GH repo to 

``
git switch dev,  git pull,  git switch feature/registration-and-login,  git rebase dev 
``

then it is ready to be pushed to the gh repo. this ensures that you have the most recent version of dev before you push. I have seen an update on dev 16+ or so hours ago from now.

**Comment by drazomo** [comment]
There was a merge conflict on package-lock.json.
deleted the package-lock.json
Simply had to reinstall the dependencies again.

**Comment by franceschiniandrea** [comment]
looks good to me

**Review by moody2times — APPROVED** [review]
Ok

**Comment by moody2times** [comment]
Manually rebased the branch and force pushed the resolution to this branch.

**Pull request merged**
